#!/usr/bin/env python3
"""
Simplified CAD generator without OpenCascade dependency
Generates STL files for 3D visualization
"""
import json
import sys
import math
import struct

def write_stl_binary(filename, triangles):
    """Write triangles to binary STL file"""
    with open(filename, 'wb') as f:
        # Header (80 bytes)
        f.write(b'Generated by Industrial Design AI' + b' ' * 46)
        
        # Number of triangles
        f.write(struct.pack('<I', len(triangles)))
        
        # Write each triangle
        for tri in triangles:
            # Normal vector (calculate from vertices)
            v1, v2, v3 = tri
            edge1 = [v2[i] - v1[i] for i in range(3)]
            edge2 = [v3[i] - v1[i] for i in range(3)]
            normal = [
                edge1[1] * edge2[2] - edge1[2] * edge2[1],
                edge1[2] * edge2[0] - edge1[0] * edge2[2],
                edge1[0] * edge2[1] - edge1[1] * edge2[0]
            ]
            length = math.sqrt(sum(n*n for n in normal))
            if length > 0:
                normal = [n/length for n in normal]
            else:
                normal = [0, 0, 1]
            
            # Write normal
            f.write(struct.pack('<fff', *normal))
            
            # Write vertices
            for vertex in tri:
                f.write(struct.pack('<fff', *vertex))
            
            # Attribute byte count
            f.write(struct.pack('<H', 0))

def generate_cylinder_mesh(radius, height, segments=32):
    """Generate triangles for a cylinder"""
    triangles = []
    
    # Generate vertices
    for i in range(segments):
        angle1 = 2 * math.pi * i / segments
        angle2 = 2 * math.pi * (i + 1) / segments
        
        x1, y1 = radius * math.cos(angle1), radius * math.sin(angle1)
        x2, y2 = radius * math.cos(angle2), radius * math.sin(angle2)
        
        # Bottom cap
        triangles.append([
            [0, 0, 0],
            [x2, y2, 0],
            [x1, y1, 0]
        ])
        
        # Top cap
        triangles.append([
            [0, 0, height],
            [x1, y1, height],
            [x2, y2, height]
        ])
        
        # Side faces (2 triangles per segment)
        triangles.append([
            [x1, y1, 0],
            [x2, y2, 0],
            [x1, y1, height]
        ])
        triangles.append([
            [x2, y2, 0],
            [x2, y2, height],
            [x1, y1, height]
        ])
    
    return triangles

def generate_box_mesh(width, height, depth):
    """Generate triangles for a box"""
    w, h, d = width/2, height/2, depth/2
    
    vertices = [
        [-w, -h, -d], [w, -h, -d], [w, h, -d], [-w, h, -d],  # Front
        [-w, -h, d], [w, -h, d], [w, h, d], [-w, h, d]       # Back
    ]
    
    faces = [
        [0, 1, 2], [0, 2, 3],  # Front
        [5, 4, 7], [5, 7, 6],  # Back
        [4, 0, 3], [4, 3, 7],  # Left
        [1, 5, 6], [1, 6, 2],  # Right
        [3, 2, 6], [3, 6, 7],  # Top
        [4, 5, 1], [4, 1, 0]   # Bottom
    ]
    
    triangles = [[vertices[i] for i in face] for face in faces]
    return triangles

def generate_torus_mesh(major_radius, minor_radius, segments=32, tube_segments=16):
    """Generate triangles for a torus"""
    triangles = []
    
    for i in range(segments):
        for j in range(tube_segments):
            # Calculate angles
            theta1 = 2 * math.pi * i / segments
            theta2 = 2 * math.pi * (i + 1) / segments
            phi1 = 2 * math.pi * j / tube_segments
            phi2 = 2 * math.pi * (j + 1) / tube_segments
            
            # Calculate vertices
            def torus_point(theta, phi):
                x = (major_radius + minor_radius * math.cos(phi)) * math.cos(theta)
                y = (major_radius + minor_radius * math.cos(phi)) * math.sin(theta)
                z = minor_radius * math.sin(phi)
                return [x, y, z]
            
            v1 = torus_point(theta1, phi1)
            v2 = torus_point(theta2, phi1)
            v3 = torus_point(theta2, phi2)
            v4 = torus_point(theta1, phi2)
            
            # Create two triangles for this quad
            triangles.append([v1, v2, v3])
            triangles.append([v1, v3, v4])
    
    return triangles

def generate_gear(params):
    """Generate gear mesh"""
    radius = params.get('radius', 25)
    thickness = params.get('thickness', 10)
    
    # Simplified: just a cylinder for now
    triangles = generate_cylinder_mesh(radius, thickness)
    return triangles

def generate_shaft(params):
    """Generate shaft mesh"""
    radius = params.get('radius', 12.5)
    length = params.get('length', 100)
    
    triangles = generate_cylinder_mesh(radius, length)
    return triangles

def generate_bearing(params):
    """Generate bearing mesh"""
    outer_radius = params.get('outerRadius', 30)
    inner_radius = params.get('innerRadius', 15)
    
    triangles = generate_torus_mesh(outer_radius, inner_radius)
    return triangles

def generate_bracket(params):
    """Generate bracket mesh"""
    width = params.get('width', 50)
    height = params.get('height', 50)
    depth = params.get('depth', 10)
    
    triangles = generate_box_mesh(width, height, depth)
    return triangles

def calculate_volume_and_mass(triangles, material='Steel'):
    """Calculate volume and mass from triangles"""
    # Simplified volume calculation
    volume = 0
    for tri in triangles:
        v1, v2, v3 = tri
        # Signed volume of tetrahedron
        volume += (v1[0] * (v2[1] * v3[2] - v2[2] * v3[1]) +
                   v2[0] * (v3[1] * v1[2] - v3[2] * v1[1]) +
                   v3[0] * (v1[1] * v2[2] - v1[2] * v2[1])) / 6.0
    
    volume = abs(volume)
    
    # Material densities (kg/m³)
    densities = {
        'Steel': 7850,
        'Aluminum': 2700,
        'Titanium': 4500,
        'Brass': 8500,
        'Copper': 8960
    }
    
    density = densities.get(material, 7850)
    mass = volume * density / 1e9  # Convert mm³ to m³ then to kg
    
    return volume, mass

def main():
    # Read design data from stdin
    design_json = sys.stdin.read()
    design_data = json.loads(design_json)
    
    component_type = design_data.get('type', 'bracket').lower()
    params = design_data.get('parameters', {})
    material = design_data.get('material', 'Steel')
    
    # Generate mesh
    generators = {
        'gear': generate_gear,
        'shaft': generate_shaft,
        'bearing': generate_bearing,
        'bracket': generate_bracket,
        'plate': generate_bracket,
        'bolt': generate_shaft  # Simplified
    }
    
    generator = generators.get(component_type, generate_bracket)
    triangles = generator(params)
    
    # Calculate properties
    volume, mass = calculate_volume_and_mass(triangles, material)
    
    # Export to STL
    output_file = f"output/{component_type}.stl"
    write_stl_binary(output_file, triangles)
    
    # Return results
    result = {
        'success': True,
        'properties': {
            'volume': volume,
            'mass': mass,
            'material': material,
            'triangles': len(triangles)
        },
        'stl_file': output_file
    }
    
    print(json.dumps(result))

if __name__ == '__main__':
    main()
